version: '3.7'
services:
  c10:
    image: akirax/moodle-c10
    ports:
      - 8003:80
      - 8004:443
    volumes:
      - moodledata:/var/moodledata
      - dbdata:/var/lib/postgresql/10/main
      - logs:/var/log
    environment:
      - DBPASS=passwd
    configs:
      - source: config_php
        target: /var/www/html/c10/config.php
      - source: config_apache2
        target: /etc/apache2/sites-enabled/c10-ssl.conf

configs:
  config_php:
    file: ./configs/config.php
  config_apache2:
    file: ./configs/c10-ssl.conf

volumes:
  moodledata:
    driver_opts:
      o: bind
      type: none
      device: /data/moodlec10/moodledata
  dbdata:
    driver_opts:
      o: bind
      type: none
      device: /data/moodlec10/dbdata
  logs:
    driver_opts:
      o: bind
      type: none
      device: /data/moodlec10/logs
